<template>
  <div id="legal-document-name-reservation-email">
    <Paper :paper-orientation="PaperOrientation.Portrait" :is-include-logo="false" :show-page-number="false"
      :additional-css-class="'legal-document name-reservation-email'">
      <template #paperContent>
        <div class="email-header">
          <table>
            <tbody>
              <tr>
                <td>To</td>
                <td>connect@icompany.my</td>
              </tr>
              <tr>
                <td>Date</td>
                <td>{{ controller.emailDate() }}</td>
              </tr>
              <tr>
                <td>Subject</td>
                <td>
                  MyCoID 2016: APPLICATION OF NAME RESERVATION - {{ controller.emailSubjectMatter() }} NOTIFICATION
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="email-content">
          <p>
            Tuan/Puan yang dihormati,
          </p>
          <p>
            Selamat Datang ke Portal MyCoID.
          </p>
          <p>
            Nama Cadangan : {{ controller.proposedName() }}<br>
            Perkara : N - NEW INCORPORATION<br>
            No. Rujukan Templet : {{ controller.application.value.ssmTemplateReferenceNumber }}<br>
            Tarikh Permohonan : {{ controller.formatDate(controller.application.value.submittedAt) }}<br>
            {{ controller.isShowResultDetails() ? 'Keputusan' : 'Status' }} : {{ controller.applicationStatus('bm') }}
          <div v-if="controller.isShowResultDetails()">
            No. Rujukan : {{ controller.application.value.ssmReferenceNumber }}<br>
            Tarikh Keputusan : {{ controller.formatDate(controller.application.value.resultAt) }}
          </div>
          </p>
          <p>
            <span v-html="controller.emailContent('bm')" />
          </p>
          <p>
            Sila hubungi kami di talian +603-7721 4000 jika menghadapi sebarang masalah.
          </p>
          <p>
            Terima kasih kerana menggunakan perkhidmatan kami. Kami mengalukan-alukan sebarang komen atau
            cadangan daripada tuan/puan untuk menambahbaik perkhidmatan kami.
          </p>
          <p>
            Salam hormat,<br>
            Admin
          </p>
          <p>
            (c)SSM - Semua hakcipta terpelihara.
          </p>
          <p>
            NOTA: INI ADALAH MESEJ YANG DIJANAKAN SECARA AUTOMATIK. MOHON TIDAK MEMBERIKAN MAKLUMBALAS KEPADA MESEJ INI.
          </p>
        </div>
      </template>
    </Paper>
    <Paper :paper-orientation="PaperOrientation.Portrait" :is-include-logo="false" :show-page-number="false"
      :additional-css-class="'legal-document name-reservation-email'">
      <template #paperContent>
        <div class="email-content">
          <p>
            Dear Sir/Madam,
          </p>
          <p>
            Welcome to the MyCoID Portal.
          </p>
          <p>
            Proposed Name : {{ controller.proposedName() }}<br>
            Subject : N - NEW INCORPORATION<br>
            Template Reference No. : {{ controller.application.value.ssmTemplateReferenceNumber }}<br>
            Request Date : {{ controller.formatDate(controller.application.value.submittedAt) }}<br>
            {{ controller.isShowResultDetails() ? 'Result' : 'Status' }} : {{ controller.applicationStatus('en') }}
          <div v-if="controller.isShowResultDetails()">
            Reference No : {{ controller.application.value.ssmReferenceNumber }}<br>
            Result Date : {{ controller.formatDate(controller.application.value.resultAt) }}
          </div>
          </p>
          <p>
            <span v-html="controller.emailContent('en')" />
          </p>
          <p>
            Kindly call us at +603-7721 4000 if you encounter any problem.
          </p>
          <p>
            Thank you for using this service. We welcome any comment or suggestion on how we can improve our services.
          </p>
          <p>
            Yours Sincerely,<br>
            Admin
          </p>
          <p>
            (c)SSM - All rights reserved.<br>
            NOTE: THIS IS AN AUTOGENERATED MESSAGE. PLEASE DO NOT REPLY TO THIS MESSAGE.
          </p>
        </div>
      </template>
    </Paper>
  </div>
</template>

<script setup lang="ts">
import Paper from '../Papers/Paper.vue'
import { NameReservationEmailController } from '~/scripts/components/legal-documents/NameReservationEmailController'
import { NameReservationEmailTypes } from '~/scripts/constants/NameReservations'
import { PaperOrientation } from '~/scripts/constants/Paper'

const props = defineProps({
  applicationId: {
    type: String,
    required: true
  },
  emailType: {
    type: String,
    required: true
  }
})

const controller = new NameReservationEmailController(props.applicationId, props.emailType as NameReservationEmailTypes)

watch(() => props.applicationId, (newVal) => {
  controller.setApplicationId(newVal)
})

watch(() => props.emailType, (newVal) => {
  controller.setEmailType(newVal as NameReservationEmailTypes)
})
</script>

<style lang="scss">
@use '~/assets/scss/components/LegalDocuments/NameReservationEmail' as *;
</style>