export type MalaysiaState =
  | "Kuala Lumpur"
  | "Selangor"
  | "Penang"
  | "Johor"
  | "Perak"
  | "Melaka"
  | "Negeri Sembilan"
  | "Pahang"
  | "Terengganu"
  | "Kelantan"
  | "Kedah"
  | "Perlis"
  | "Sabah"
  | "Sarawak"
  | "Putrajaya"
  | "Labuan"
